### ISSUE TITLE
单位建议：星舰组装厂

### ISSUE THREAD

**Issue by gedrode** [woodjecket/CommunDustry#9]
组装一些没有明显等级之分（可能吧）的“星舰”空军（使用组装厂）
护卫舰-流星
驱逐舰-炫星
巡洋舰-彗星
战列舰-灾祸（额外的组装厂模块）
航母-星海（额外的组装厂模块）

**Comment by gedrode** [comment]
可以的话我会提供贴图（）
_如果通过的话_

**Comment by gedrode** [comment]
那要照这么搞是不是可以搓空间站和太空战（）

**Comment by 430230562** [comment]
emmm，这样一来看,地图就完全脱离星球了呢

**Comment by lyrgo** [comment]
> 

### 这得咋写啊

**Comment by gedrode** [comment]
> > 
> 
> ### 这得咋写啊

目前先只实现单位不就得了（大草）
